In [1]:
from sklearn import svm
import numpy as np

In [ ]:
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])

In [ ]:
clf = svm.SVC()

In [ ]:
clf.fit(X,y)

Predict 1 point

In [ ]:
clf.predict([[-0.8, -1]])

Predict 3 points

In [ ]:
clf.predict([[0., 1.], [5, 6], [-1, 5]])

get support vectors

In [ ]:
clf.support_vectors_

get indices of support vectors

In [ ]:
clf.support_

get number of support vectors for each class

In [ ]:
clf.n_support_

# Multi-class classification

## one-versus-one

In [2]:
X = [[0], [1], [2], [3]]
Y = [0, 1, 2, 3]

In [ ]:
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X,Y)

In [ ]:
dec = clf.decision_function([[1]])
dec.shape[1]

In [ ]:
clf.predict([[1.2]])

In [ ]:
clf.predict([[1.2], [2.6], [-5.]])

## one-versus-rest

In [3]:
lin_clf = svm.LinearSVC()
lin_clf.fit(X, Y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [4]:
dec = lin_clf.decision_function([[1]])
dec.shape[1]

4L

In [5]:
lin_clf.predict([[1.2], [2.6], [-5.]])

array([1, 3, 0])

In [6]:
lin_clf.coef_

array([[-0.90908744],
       [-0.20513621],
       [ 0.10255951],
       [ 0.41023297]])

In [7]:
lin_clf.intercept_

array([ 0.36363116, -0.17093297, -0.58121676, -0.99145676])

## Regression

In [8]:
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]

In [9]:
clf = svm.SVR()
clf.fit(X,y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [10]:
clf.predict([[1.2, 3]])

array([ 1.89882666])